package main
import ("context";"encoding/json";"net/http";"os";"github.com/go-chi/chi/v5";"github.com/jackc/pgx/v5/pgxpool";"hypercompute/shared")
func main(){db,_:=pgxpool.New(context.Background(),getenv("DATABASE_URL","postgres://postgres:postgres@postgres:5432/hypercompute?sslmode=disable"));r:=chi.NewRouter();r.Get("/health",func(w http.ResponseWriter,r *http.Request){w.Write([]byte("ok"))});r.Get("/metrics",func(w http.ResponseWriter,r *http.Request){w.Write([]byte("wallet_up 1"))});
r.Post("/wallets",func(w http.ResponseWriter,r *http.Request){var b struct{UserID int `json:"user_id"`};json.NewDecoder(r.Body).Decode(&b);_,_=db.Exec(r.Context(),"insert into wallet_accounts(user_id,balance,hold_balance,updated_at) values($1,0,0,now()) on conflict (user_id) do nothing",b.UserID);json.NewEncoder(w).Encode(map[string]any{"ok":true})});
r.Get("/wallets/{uid}",func(w http.ResponseWriter,r *http.Request){uid:=chi.URLParam(r,"uid");var bal float64;_ = db.QueryRow(r.Context(),"select balance from wallet_accounts where user_id=$1",uid).Scan(&bal);json.NewEncoder(w).Encode(map[string]any{"balance":bal})});
r.Post("/topup",func(w http.ResponseWriter,r *http.Request){var b struct{UserID int `json:"user_id"`;Amount float64 `json:"amount"`};json.NewDecoder(r.Body).Decode(&b);tx,_:=db.Begin(r.Context());defer tx.Rollback(r.Context());_,_=tx.Exec(r.Context(),"insert into wallet_accounts(user_id,balance,hold_balance,updated_at) values($1,0,0,now()) on conflict (user_id) do nothing",b.UserID);_,_=tx.Exec(r.Context(),"update wallet_accounts set balance=balance+$1 where user_id=$2",b.Amount,b.UserID);_,_=tx.Exec(r.Context(),"insert into wallet_transactions(user_id,amount,tx_type,ref_id,created_at) values($1,$2,'TOPUP',gen_random_uuid()::text,now())",b.UserID,b.Amount);_ = tx.Commit(r.Context());json.NewEncoder(w).Encode(map[string]any{"ok":true})});
r.Post("/hold",func(w http.ResponseWriter,r *http.Request){var b struct{UserID int `json:"user_id"`;Amount float64 `json:"amount"`;RefID string `json:"ref_id"`};json.NewDecoder(r.Body).Decode(&b);_,_=db.Exec(r.Context(),"insert into wallet_holds(user_id,ref_id,amount,status,created_at) values($1,$2,$3,'HELD',now()) on conflict(ref_id) do nothing",b.UserID,b.RefID,b.Amount);_,_=db.Exec(r.Context(),"update wallet_accounts set hold_balance=hold_balance+$1 where user_id=$2",b.Amount,b.UserID);json.NewEncoder(w).Encode(map[string]any{"ok":true})});
r.Post("/capture",func(w http.ResponseWriter,r *http.Request){var b struct{UserID int `json:"user_id"`;Amount float64 `json:"amount"`;RefID string `json:"ref_id"`};json.NewDecoder(r.Body).Decode(&b);_,_=db.Exec(r.Context(),"update wallet_accounts set balance=balance-$1,hold_balance=greatest(hold_balance-$1,0) where user_id=$2",b.Amount,b.UserID);_,_=db.Exec(r.Context(),"insert into wallet_transactions(user_id,amount,tx_type,ref_id,created_at) values($1,$2,'CAPTURE',$3,now())",b.UserID,-b.Amount,b.RefID);json.NewEncoder(w).Encode(map[string]any{"ok":true})});
r.Post("/release",func(w http.ResponseWriter,r *http.Request){json.NewEncoder(w).Encode(map[string]any{"ok":true})});
http.ListenAndServe(":8082",r);_ = shared.ErrorBody{}}
func getenv(k,d string)string{v:=os.Getenv(k);if v==""{return d};return v}
