package main
import (
 "context";"crypto/sha256";"encoding/hex";"encoding/json";"fmt";"log";"net/http";"os";"time"
 "github.com/go-chi/chi/v5";"github.com/google/uuid";"github.com/jackc/pgx/v5/pgxpool";"hypercompute/shared")
func main(){dsn:=os.Getenv("DATABASE_URL");if dsn==""{dsn="postgres://postgres:postgres@postgres:5432/hypercompute?sslmode=disable"};db,err:=pgxpool.New(context.Background(),dsn);if err!=nil{panic(err)};defer db.Close();r:=chi.NewRouter();r.Get("/health",func(w http.ResponseWriter,r *http.Request){w.Write([]byte("ok"))});r.Get("/metrics",func(w http.ResponseWriter,r *http.Request){w.Write([]byte("auth_up 1"))});
r.Post("/users",func(w http.ResponseWriter,r *http.Request){var b struct{Email string `json:"email"`};json.NewDecoder(r.Body).Decode(&b);var id int;_ = db.QueryRow(r.Context(),"insert into users(email,created_at) values($1,now()) on conflict (email) do update set email=excluded.email returning id",b.Email).Scan(&id);json.NewEncoder(w).Encode(map[string]any{"id":id,"email":b.Email})});
r.Post("/api-keys",func(w http.ResponseWriter,r *http.Request){var b struct{UserID int `json:"user_id"`};json.NewDecoder(r.Body).Decode(&b);raw:="hc_live_"+uuid.NewString()[:18];h:=sha256.Sum256([]byte(raw));_,_ = db.Exec(r.Context(),"insert into api_keys(user_id,key_hash,created_at) values($1,$2,now())",b.UserID,hex.EncodeToString(h[:]));json.NewEncoder(w).Encode(map[string]any{"api_key":raw})});
r.Post("/validate",func(w http.ResponseWriter,r *http.Request){var b struct{APIKey string `json:"api_key"`};json.NewDecoder(r.Body).Decode(&b);h:=sha256.Sum256([]byte(b.APIKey));var uid int;err:=db.QueryRow(r.Context(),"select user_id from api_keys where key_hash=$1 order by id desc limit 1",hex.EncodeToString(h[:])).Scan(&uid);if err!=nil{shared.WriteError(w,401,"invalid api key","INVALID_API_KEY");return};json.NewEncoder(w).Encode(map[string]any{"valid":true,"user_id":uid})});
addr:=":"+getenv("PORT","8086");s:=&http.Server{Addr:addr,Handler:r};go func(){<-context.Background().Done()}();log.Printf("auth %s",addr);if err:=s.ListenAndServe();err!=nil{fmt.Println(err)};time.Sleep(1*time.Millisecond)}
func getenv(k,d string)string{v:=os.Getenv(k);if v==""{return d};return v}
